// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[...id].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/about/_titles.ts";
import * as $4 from "./routes/about/contact.tsx";
import * as $5 from "./routes/about/corpus.tsx";
import * as $6 from "./routes/about/index.tsx";
import * as $7 from "./routes/about/permissions.tsx";
import * as $8 from "./routes/about/principles.tsx";
import * as $9 from "./routes/about/support.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/research/_data.tsx";
import * as $12 from "./routes/research/_titles.ts";
import * as $13 from "./routes/research/index.tsx";
import * as $14 from "./routes/research/similarity.tsx";
import * as $15 from "./routes/research/topics.tsx";
import * as $$0 from "./islands/AuthorDisplay.tsx";
import * as $$1 from "./islands/Controls.tsx";
import * as $$2 from "./islands/Info.tsx";
import * as $$3 from "./islands/Library.tsx";
import * as $$4 from "./islands/Query.tsx";
import * as $$5 from "./islands/Results.tsx";
import * as $$6 from "./islands/Search.tsx";
import * as $$7 from "./islands/TextDisplay.tsx";

const manifest = {
  routes: {
    "./routes/[...id].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/about/_titles.ts": $3,
    "./routes/about/contact.tsx": $4,
    "./routes/about/corpus.tsx": $5,
    "./routes/about/index.tsx": $6,
    "./routes/about/permissions.tsx": $7,
    "./routes/about/principles.tsx": $8,
    "./routes/about/support.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/research/_data.tsx": $11,
    "./routes/research/_titles.ts": $12,
    "./routes/research/index.tsx": $13,
    "./routes/research/similarity.tsx": $14,
    "./routes/research/topics.tsx": $15,
  },
  islands: {
    "./islands/AuthorDisplay.tsx": $$0,
    "./islands/Controls.tsx": $$1,
    "./islands/Info.tsx": $$2,
    "./islands/Library.tsx": $$3,
    "./islands/Query.tsx": $$4,
    "./islands/Results.tsx": $$5,
    "./islands/Search.tsx": $$6,
    "./islands/TextDisplay.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
