// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[...id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_titles from "./routes/about/_titles.ts";
import * as $about_contact from "./routes/about/contact.tsx";
import * as $about_corpus from "./routes/about/corpus.tsx";
import * as $about_index from "./routes/about/index.tsx";
import * as $about_permissions from "./routes/about/permissions.tsx";
import * as $about_principles from "./routes/about/principles.tsx";
import * as $about_support from "./routes/about/support.tsx";
import * as $index from "./routes/index.tsx";
import * as $research_data from "./routes/research/_data.tsx";
import * as $research_titles from "./routes/research/_titles.ts";
import * as $research_index from "./routes/research/index.tsx";
import * as $research_similarity from "./routes/research/similarity.tsx";
import * as $research_topics from "./routes/research/topics.tsx";
import * as $AuthorDisplay from "./islands/AuthorDisplay.tsx";
import * as $Controls from "./islands/Controls.tsx";
import * as $DissertationSimilarityTable from "./islands/DissertationSimilarityTable.tsx";
import * as $EMPLSimilarityTable from "./islands/EMPLSimilarityTable.tsx";
import * as $Info from "./islands/Info.tsx";
import * as $Library from "./islands/Library.tsx";
import * as $Query from "./islands/Query.tsx";
import * as $Results from "./islands/Results.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $TextDisplay from "./islands/TextDisplay.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/about/_titles.ts": $about_titles,
    "./routes/about/contact.tsx": $about_contact,
    "./routes/about/corpus.tsx": $about_corpus,
    "./routes/about/index.tsx": $about_index,
    "./routes/about/permissions.tsx": $about_permissions,
    "./routes/about/principles.tsx": $about_principles,
    "./routes/about/support.tsx": $about_support,
    "./routes/index.tsx": $index,
    "./routes/research/_data.tsx": $research_data,
    "./routes/research/_titles.ts": $research_titles,
    "./routes/research/index.tsx": $research_index,
    "./routes/research/similarity.tsx": $research_similarity,
    "./routes/research/topics.tsx": $research_topics,
  },
  islands: {
    "./islands/AuthorDisplay.tsx": $AuthorDisplay,
    "./islands/Controls.tsx": $Controls,
    "./islands/DissertationSimilarityTable.tsx": $DissertationSimilarityTable,
    "./islands/EMPLSimilarityTable.tsx": $EMPLSimilarityTable,
    "./islands/Info.tsx": $Info,
    "./islands/Library.tsx": $Library,
    "./islands/Query.tsx": $Query,
    "./islands/Results.tsx": $Results,
    "./islands/Search.tsx": $Search,
    "./islands/TextDisplay.tsx": $TextDisplay,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
